version: 0.2

env:
  variables:
   GOOS: "linux"
   GOARCH: "amd64"
phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - env
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  pre_build:
    commands:
      - export GOBIN=$GOPATH/bin
      # - cd $CODEBUILD_SRC_DIR
      - go get -t ./...
      - go test ./...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main
